# Site settings
title: wangrongwei's world
email: rongwei.wrw
site_name: lollipop
pages: blog notice
plugins:
 - jekyll-sitemap

# basic configure
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# this means to ignore newlines until "baseurl:"
description: 个人博客

# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://wangrongwei.com"
#twitter_username: jekyllrb
github_username:  wangrongwei

# Disqus settings（https://disqus.com/）
disqus_shortname: zackarywong

# Build settings


permalink: /:year/:month/:day/:title.html