
# Site settings
title: lollipop's homepage
email: rongwei.lisp
site_name: lollipop

# this means to ignore newlines until "baseurl:"
description: 个人博客

# the subpath of your site, e.g. /blog/
baseurl: ""

# the base hostname & protocol for your site
url: "http://wangrongwei.com"

#twitter_username: jekyllrb
github_username:  wangrongwei

# Disqus settings（https://disqus.com/）
disqus_username: Zackary Wong
disqus: Zackary Wong

# Build settings


permalink: /:year/:month/:day/:title.html

