
# Site settings
title: wangrongwei's world
email: rongwei.lisp@gmail.com
description: 个人博客 # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wangrongwei.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wangrongwei

# Disqus settings（https://disqus.com/）
disqus_username: Zackary Wong
disqus: Evan

# Build settings


permalink: /:year/:month/:day/:title.html

